- name:  Fact | mysql_configuration_version
  set_fact: mysql_configuration_version=7
  when: "mysql_type == 'vendor' or mysql_type == 'mariadb'"

- name: Fact | mysql_configuration_version
  set_fact: mysql_configuration_version=5
  when: >
    mysql_type == 'system' and (
      ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14 or
      ansible_distribution == 'Debian' and ansible_distribution_major_version|int <= 8
    )

- name: Fact | mysql_configuration_version
  set_fact: mysql_configuration_version=7
  when: >
    mysql_type == 'system' and (
      ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 14 or
      ansible_distribution == 'Debian' and ansible_distribution_major_version|int > 8
    )

- name: Fact | MySQL etc dir
  set_fact: mysql_etc_d=/etc/mysql/conf.d
  when: >
    (mysql_configuration_version|int <= 5) or 
    (mysql_type == "mariadb") or 
    (
      mysql_type == "system" and mysql_configuration_version|int >= 6 and 
      ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14
    )

- name: Fact | MySQL etc dir
  set_fact: mysql_etc_d=/etc/mysql/mysql.conf.d
  when: >
    mysql_type == "vendor" or 
    (
      mysql_type == "system" and mysql_configuration_version|int > 5 and 
      not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14)
    )
