################################################
## System
################################################
- block:
  - set_fact:
      mysql_configuration_version: "mariadb"
      mysql_apt:
        - mariadb-server
        - mariadb-client
        - python-mysqldb
        - python-sqlalchemy
        - python-pymysql
      mysql_etc_d: "/etc/mysql/mariadb.conf.d"
      mysql_service_d: "/etc/systemd/system/mariadb.service.d/mysql_tuning.conf"
    when: ansible_distribution_release == "buster"

  - set_fact:
      mysql_configuration_version: "mariadb"
      mysql_apt:
        - mariadb-server
        - mariadb-client
        - python-mysqldb
        - python-sqlalchemy
        - python-pymysql
      mysql_etc_d: "/etc/mysql/mariadb.conf.d"
      mysql_service_d: "/etc/systemd/system/mariadb.service.d/mysql_tuning.conf"
    when: ansible_distribution_release == "stretch"

  - set_fact:
      mysql_configuration_version: "mysql"
      mysql_apt:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python-sqlalchemy
        - python-pymysql
      mysql_etc_d: "/etc/mysql/mysql.conf.d"
      mysql_service_d: "/etc/systemd/system/mysql.service.d/mysql_tuning.conf"
    when: ansible_distribution_release == "xenial"

  - set_fact:
      mysql_configuration_version: "mysql"
      mysql_apt:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python-sqlalchemy
        - python-pymysql
      mysql_etc_d: "/etc/mysql/mysql.conf.d"
      mysql_service_d: "/etc/systemd/system/mysql.service.d/mysql_tuning.conf"
    when: ansible_distribution_release == "bionic"
  when: not mysql_vendor is defined

################################################
## MariaDB
################################################

- set_fact:
    mysql_configuration_version: "mariadb"
    mysql_apt:
      - mariadb-server
      - mariadb-client
      - python-mysqldb
      - python-sqlalchemy
      - python-pymysql
    mysql_apt_repo: "deb [arch=amd64,i386] http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.4/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    mysql_apt_repo_filename: "mariadb"
    mysql_apt_keys:
      - "0xF1656F24C74CD1D8"
      - "0xcbcb082a1bb943db"
    mysql_etc_d: "/etc/mysql/conf.d"
    mysql_service_d: "/etc/systemd/system/mariadb.service.d/mysql_tuning.conf"
  when: mysql_vendor is defined and mysql_vendor == "mariadb"
