- name: Fact | MySQL etc dir
  set_fact: mysql_etc_d=/etc/mysql/conf.d
  when: mysql_optimization_version|int <= 5

- name: Fact | MySQL etc dir
  set_fact: mysql_etc_d=/etc/mysql/mysql.conf.d
  when: mysql_optimization_version|int > 5

- name: Create configuration directory
  file: path={{ mysql_etc_d }} state=directory owner=root group=root mode=755

# It is important to set innodb_log_file_size in the configuration before the first mysql launch!
- name: mysql configuration
  template: src=optimization.cnf.j2 dest={{ mysql_etc_d }}/zz_00_optimization.cnf

- name: Install MySQL
  apt: name={{ item }}
  with_items:
    - "{{ mysql_server_package_debian }}"
    - "{{ mysql_client_package_debian }}"
    - python-mysqldb
  when: ansible_pkg_mgr == "apt"

- name: Fetch root password
  mysql_password_ini: path=/root/.my.cnf user=root
  register: mysql_data

- name: Update root user
  mysql_user: host=localhost user={{ mysql_data.user }} password={{ mysql_data.password }} check_implicit_admin=yes update_password=always

- name: Write mysql credentials
  ini_file: dest=/root/.my.cnf section=client option={{ item.option }} value={{ item.value }} create=yes
  with_items:
    - option: user
      value: "{{ mysql_data.user }}"
    - option: password
      value: "{{ mysql_data.password }}"

- name: Update root user for all hosts
  mysql_user: host_all=yes user={{ mysql_data.user }} password={{ mysql_data.password }} update_password=always

- name: Backup script
  template: src=mysqlbackup.j2 dest=/usr/local/bin/mysqlbackup owner=root group=root mode=0755

- name: Backup cronjob
  cron:
    name: mysql backup
    cron_file: mysql_backup
    user: root
    job: /usr/local/bin/mysqlbackup
    minute: "{{ mysql_backup_minute }}"
    hour: "{{ mysql_backup_hour }}"
